### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by bluet** [agsh/broviki#3]
Browsing to https://localhost:6900/ only shows a text 'Cannot GET /', no error msg in console.

**Comment by agsh** [comment]
Sorry, this is a pet project to replace [ONVIF Device Manager](http://sourceforge.net/projects/onvifdm/) in web with node.js and onvif,js, not only windows,
And you can find there only authorization form. Just about your question, you should build client with gulp. I have no time to work on this.
If you want to work on this project, I'll gladly add you to developers, or give this project to you.

**Comment by bluet** [comment]
I've read about the project README and that's why I started testing. This is a cool project which might help a lot of people, and shouldn't be stoppped! :-)
I'll see what I can help, but before that I guess I have to run it successfully to figure out the logic, hahaha.

As I'm really not a frontend guy, could you point out some instructions?

**Comment by bluet** [comment]
After installing gulp `npm install gulp` and run it `matthew@0xB1uE7:~/tmp/broviki$ ./node_modules/gulp/bin/gulp.js all`, I got error:

matthew@0xB1uE7:~/tmp/broviki$ ./node_modules/gulp/bin/gulp.js all
[00:42:06] Using gulpfile ~/tmp/broviki/gulpfile.js
[00:42:06] Starting 'jade'...
[00:42:06] Finished 'jade' after 7.45 ms
[00:42:06] Starting 'less to css'...
[00:42:06] Finished 'less to css' after 12 ms
[00:42:06] Starting 'browserify js'...
[00:42:06] Finished 'browserify js' after 5.98 ms
[00:42:06] Starting 'index'...
[00:42:06] Finished 'index' after 609 μs
[00:42:06] Starting 'all'...
[00:42:06] Finished 'all' after 5.44 μs

_stream_readable.js:583
    var written = dest.write(chunk);
                       ^
TypeError: Object #<Readable> has no method 'write'
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at _stream_readable.js:560:7
    at process._tickCallback (node.js:415:13)
matthew@0xB1uE7:~/tmp/broviki$ node -v
v0.10.22

**Comment by agsh** [comment]
Thanks for feedback! The reason of this error is new behaviour of gulp-browserify plugin. I've fixed this in repo. Also added `npm run build` command to package.json to build client

**Comment by bluet** [comment]
matthew@0xB1uE7:~/workspace/broviki$ ./node_modules/gulp/bin/gulp.js all

Error: Cannot find module 'vinyl-source-stream'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/matthew/workspace/broviki/gulpfile.js:12:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

After installing `npm install vinyl-source-stream` it builds.

**Comment by bluet** [comment]
https://github.com/agsh/broviki/pull/4

**Comment by bluet** [comment]
server/app.js runs now with
'started at port 6900'

I can see the port opened via `sudo netstat -ntupl|grep 6900`
'tcp        0      0 0.0.0.0:6900            0.0.0.0:\*               LISTEN      29785/node'

But open http://127.0.0.1:6900 will stay in 'connected' state and it never return anything.
Same when using telnet to test:
matthew@0xB1uE7:~/workspace/broviki$ telnet localhost 6900
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.0

^C^]

telnet> quit
Connection closed.

**Comment by bluet** [comment]
runing `npm run test` shows lots of error:

matthew@0xB1uE7:~/workspace/broviki$ npm run test

> Broviki@0.0.1 test /home/matthew/workspace/broviki
> ./node_modules/.bin/mocha

  Users module
    Simple test
      ✓ should return test response (79ms)
    New user creation
      ✓ should not create a new user if fields is missing (48ms)
ReferenceError: Promise is not defined
    at Datastore.insert (/home/matthew/workspace/broviki/server/js/db.js:45:14)
    at Object.database.users.add (/home/matthew/workspace/broviki/server/js/db.js:128:4)
    at signup (/home/matthew/workspace/broviki/server/js/users.js:43:18)
    at Layer.handle [as handle_request](/home/matthew/workspace/broviki/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/matthew/workspace/broviki/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/matthew/workspace/broviki/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/home/matthew/workspace/broviki/node_modules/express/lib/router/layer.js:95:5)
    at /home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:330:12)
    at next (/home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:271:10)
    at /home/matthew/workspace/broviki/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
      1) should create a new user
ReferenceError: Promise is not defined
    at Datastore.insert (/home/matthew/workspace/broviki/server/js/db.js:45:14)
    at Object.database.users.add (/home/matthew/workspace/broviki/server/js/db.js:128:4)
    at signup (/home/matthew/workspace/broviki/server/js/users.js:43:18)
    at Layer.handle [as handle_request](/home/matthew/workspace/broviki/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/matthew/workspace/broviki/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/matthew/workspace/broviki/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/home/matthew/workspace/broviki/node_modules/express/lib/router/layer.js:95:5)
    at /home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:330:12)
    at next (/home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:271:10)
    at /home/matthew/workspace/broviki/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
      2) should create existing user
    Login
ReferenceError: Promise is not defined
    at promisifyDb (/home/matthew/workspace/broviki/server/js/db.js:60:13)
    at Object.database.users.getUser (/home/matthew/workspace/broviki/server/js/db.js:115:9)
    at login (/home/matthew/workspace/broviki/server/js/users.js:26:17)
    at Layer.handle [as handle_request](/home/matthew/workspace/broviki/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/matthew/workspace/broviki/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/matthew/workspace/broviki/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/home/matthew/workspace/broviki/node_modules/express/lib/router/layer.js:95:5)
    at /home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:330:12)
    at next (/home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:271:10)
    at /home/matthew/workspace/broviki/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
      3) should fail with unexisting user
ReferenceError: Promise is not defined
    at promisifyDb (/home/matthew/workspace/broviki/server/js/db.js:60:13)
    at Object.database.users.getUser (/home/matthew/workspace/broviki/server/js/db.js:115:9)
    at login (/home/matthew/workspace/broviki/server/js/users.js:26:17)
    at Layer.handle [as handle_request](/home/matthew/workspace/broviki/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/matthew/workspace/broviki/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/matthew/workspace/broviki/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/home/matthew/workspace/broviki/node_modules/express/lib/router/layer.js:95:5)
    at /home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:330:12)
    at next (/home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:271:10)
    at /home/matthew/workspace/broviki/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
      4) should fail with wrong credentials
ReferenceError: Promise is not defined
    at promisifyDb (/home/matthew/workspace/broviki/server/js/db.js:60:13)
    at Object.database.users.getUser (/home/matthew/workspace/broviki/server/js/db.js:115:9)
    at login (/home/matthew/workspace/broviki/server/js/users.js:26:17)
    at Layer.handle [as handle_request](/home/matthew/workspace/broviki/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/matthew/workspace/broviki/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/matthew/workspace/broviki/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/home/matthew/workspace/broviki/node_modules/express/lib/router/layer.js:95:5)
    at /home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:330:12)
    at next (/home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:271:10)
    at /home/matthew/workspace/broviki/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
      5) should login with proper credentials
    Remove user
ReferenceError: Promise is not defined
    at Datastore.remove (/home/matthew/workspace/broviki/server/js/db.js:45:14)
    at Object.database.users.remove (/home/matthew/workspace/broviki/server/js/db.js:142:18)
    at remove (/home/matthew/workspace/broviki/server/js/users.js:55:17)
    at Layer.handle [as handle_request](/home/matthew/workspace/broviki/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/matthew/workspace/broviki/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/matthew/workspace/broviki/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/home/matthew/workspace/broviki/node_modules/express/lib/router/layer.js:95:5)
    at /home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:330:12)
    at next (/home/matthew/workspace/broviki/node_modules/express/lib/router/index.js:271:10)
    at /home/matthew/workspace/broviki/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/home/matthew/workspace/broviki/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
      6) should remove user from database

  2 passing (644ms)
  6 failing

  1) Users module New user creation should create a new user:

```
  Uncaught AssertionError: false == true
  + expected - actual

  -false
  +true

  at Request._callback (test/users.js:46:12)
  at Request.self.callback (node_modules/request/request.js:198:22)
  at Request.<anonymous> (node_modules/request/request.js:1082:10)
  at IncomingMessage.<anonymous> (node_modules/request/request.js:1009:12)
  at _stream_readable.js:920:16
```

  2) Users module New user creation should create existing user:

```
  Uncaught AssertionError: false == true
  + expected - actual

  -false
  +true

  at Request._callback (test/users.js:60:12)
  at Request.self.callback (node_modules/request/request.js:198:22)
  at Request.<anonymous> (node_modules/request/request.js:1082:10)
  at IncomingMessage.<anonymous> (node_modules/request/request.js:1009:12)
  at _stream_readable.js:920:16
```

  3) Users module Login should fail with unexisting user:

```
  Uncaught AssertionError: false == true
  + expected - actual

  -false
  +true

  at Request._callback (test/users.js:76:12)
  at Request.self.callback (node_modules/request/request.js:198:22)
  at Request.<anonymous> (node_modules/request/request.js:1082:10)
  at IncomingMessage.<anonymous> (node_modules/request/request.js:1009:12)
  at _stream_readable.js:920:16
```

  4) Users module Login should fail with wrong credentials:

```
  Uncaught AssertionError: false == true
  + expected - actual

  -false
  +true

  at Request._callback (test/users.js:89:12)
  at Request.self.callback (node_modules/request/request.js:198:22)
  at Request.<anonymous> (node_modules/request/request.js:1082:10)
  at IncomingMessage.<anonymous> (node_modules/request/request.js:1009:12)
  at _stream_readable.js:920:16
```

  5) Users module Login should login with proper credentials:

```
  Uncaught AssertionError: false == true
  + expected - actual

  -false
  +true

  at Request._callback (test/users.js:102:12)
  at Request.self.callback (node_modules/request/request.js:198:22)
  at Request.<anonymous> (node_modules/request/request.js:1082:10)
  at IncomingMessage.<anonymous> (node_modules/request/request.js:1009:12)
  at _stream_readable.js:920:16
```

  6) Users module Remove user should remove user from database:

```
  Uncaught AssertionError: false == true
  + expected - actual

  -false
  +true

  at Request._callback (test/users.js:117:12)
  at Request.self.callback (node_modules/request/request.js:198:22)
  at Request.<anonymous> (node_modules/request/request.js:1082:10)
  at IncomingMessage.<anonymous> (node_modules/request/request.js:1009:12)
  at _stream_readable.js:920:16
```

npm ERR! Broviki@0.0.1 test: `./node_modules/.bin/mocha`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the Broviki@0.0.1 test script.
npm ERR! This is most likely a problem with the Broviki package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/.bin/mocha
npm ERR! You can get their info via:
npm ERR!     npm owner ls Broviki
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-30-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! cwd /home/matthew/workspace/broviki
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/matthew/workspace/broviki/npm-debug.log
npm ERR! not ok code 0
